Testing material UI
nadiyniy/booking-cinema-tickets pull request #1
Opened 2024-01-19 10:46 UTC by nadiyniy

2024-01-21 21:17 UTC, mike-gusiev requested changes

2024-01-21 21:17 UTC, mike-gusiev commented on src/App.jsx
> +import { getReservationsSeat, getSessionDetails, getSessions } from './services/api.js';
в папці src/components створи файл index.js. щоб всі компоненти можна було імпортувати одним рядком

2024-01-21 21:17 UTC, mike-gusiev commented on src/components/ConfirmSeat/ConfirmSeat.jsx
> +function ConfirmSeat({ selectedSeat, onReservedSeat, error, isLoading }) {
використовуй коротку форму es6 функцій без return, там де це можливо

2024-01-21 21:17 UTC, mike-gusiev commented on src/components/ConfirmSeat/ConfirmSeat.jsx
> +import DoneIcon from '@mui/icons-material/Done';
позбудься зайвих папок в src/components. не треба створювати папку якщо там один файл лежить

2024-01-21 21:17 UTC, mike-gusiev commented on src/components/Home/StyledHome.jsx
> +import styled from 'styled-components';
створи папку src/styled. і туди повиноси усі styled components у вигляді окремих файлів. структура папок в src/styled повинна дублювати структуру папок в src/components

2024-01-21 21:17 UTC, mike-gusiev commented on src/components/SessionList/SessionList.jsx
>  }
позбудься папки src/images. усі картинки мають лежати в папці public і грузитися через http запити

2024-01-21 21:17 UTC, mike-gusiev commented on src/index.css
>  body {
позбудься css файлів. всі стилі, включаючи глобальні, повинні бути styled components

2024-01-21 21:23 UTC, nadiyniy commented
ОкейOn 21 Jan 2024, at 23:17, mike-gusiev ***@***.***> wrote:﻿
@mike-gusiev requested changes on this pull request.



In src/App.jsx:
>  import React, { useState, useEffect } from 'react';
-import { getReservationsSeat, getSessionDetails, getSessions } from './services/api';
-import SelectDate from './components/SelectDate/SelectDate';
-import SessionList from './components/SessionList/SessionList';
-import SeatList from './components/SeatList/SeatList';
-import ConfirmSeat from './components/ConfirmSeat/ConfirmSeat';
+import { Container } from ***@***.***/material';
+import { Navigate, Route, Routes, useNavigate } from 'react-router-dom';
+import { getReservationsSeat, getSessionDetails, getSessions } from './services/api.js';

в папці src/components створи файл index.js. щоб всі компоненти можна було імпортувати одним рядком



In src/components/ConfirmSeat/ConfirmSeat.jsx:
>  import PropTypes from 'prop-types';
 
-function ConfirmSeat({ selectedSeat, onReservedSeat, error }) {
+function ConfirmSeat({ selectedSeat, onReservedSeat, error, isLoading }) {

використовуй коротку форму es6 функцій без return, там де це можливо



In src/components/ConfirmSeat/ConfirmSeat.jsx:
> @@ -1,14 +1,27 @@
+import DoneIcon from ***@***.***/icons-material/Done';

позбудься зайвих папок в src/components. не треба створювати папку якщо там один файл лежить



In src/components/Home/StyledHome.jsx:
> @@ -0,0 +1,16 @@
+import styled from 'styled-components';

створи папку src/styled. і туди повиноси усі styled components у вигляді окремих файлів. структура папок в src/styled повинна дублювати структуру папок в src/components



In src/components/SessionList/SessionList.jsx:
>                  ))}
-            </ul>
+            </Grid>
         </>
     );
 }

позбудься папки src/images. усі картинки мають лежати в папці public і грузитися через http запити



In src/index.css:
> @@ -104,6 +104,11 @@ section {
 body {

позбудься css файлів. всі стилі, включаючи глобальні, повинні бути styled components

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-01-22 09:33 UTC, nadiyniy commented on src/App.jsx
> +import { getReservationsSeat, getSessionDetails, getSessions } from './services/api.js';
✅

2024-01-22 09:33 UTC, nadiyniy commented on src/components/ConfirmSeat/ConfirmSeat.jsx
> +function ConfirmSeat({ selectedSeat, onReservedSeat, error, isLoading }) {
✅

2024-01-22 09:33 UTC, nadiyniy commented on src/components/ConfirmSeat/ConfirmSeat.jsx
> +import DoneIcon from '@mui/icons-material/Done';
✅

2024-01-22 10:06 UTC, nadiyniy commented on src/index.css
>  body {
✅

2024-01-22 10:33 UTC, merged