fix fetch sessions, fix url background, delete unused file
nadiyniy/booking-cinema-tickets pull request #2
Opened 2024-01-22 10:53 UTC by nadiyniy

2024-01-22 22:16 UTC, mike-gusiev requested changes

2024-01-22 22:16 UTC, mike-gusiev commented on src/components/SeatList.jsx
> +function SeatList({ seats, handleSeatClick, reservedSeat, selectedSeat }) {
використовуй коротку форму es6 функцій без return, там де це можливо

2024-01-22 22:16 UTC, mike-gusiev commented on src/components/SeatList.jsx
> +    const Item = styled(Paper)(({ theme, reserved, isSelected }) => ({
створи папку src/styled. і туди повиноси усі styled components у вигляді окремих файлів. структура папок в src/styled повинна дублювати структуру папок в src/components

2024-01-22 22:16 UTC, mike-gusiev commented on src/components/SeatList.jsx
>          backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
створи файл для глобальних змінних styled components. і туди повиносили всі кольори і розміри в медіа запитах

2024-01-22 22:16 UTC, mike-gusiev commented on src/redux/seats/actions.js
> +import { SET_CONFIRMED_SEAT, SET_ERROR_SEAT, SET_RESERVED_SEATS, SET_SEATS, SET_SELECTED_SEAT } from './constants';
структура редаксу трохи неправильна. позбудься папки reducers. і створи папку src/redux/ducks. і туди в окремі файли помісти усі екшени/редюсери/саги і тд одним файлом. все що відноситься до одного duck - має бути в одному файлі:
https://github.com/erikras/ducks-modular-redux

2024-01-23 09:07 UTC, nadiyniy commented on src/components/SeatList.jsx
> +function SeatList({ seats, handleSeatClick, reservedSeat, selectedSeat }) {
мені потрібно в компонентах ретурн прибрати? єслінт видає помилку Function component is not a function declaration

2024-01-23 09:07 UTC, nadiyniy commented on src/components/SeatList.jsx
> +    const Item = styled(Paper)(({ theme, reserved, isSelected }) => ({
✅

2024-01-23 09:07 UTC, nadiyniy commented on src/components/SeatList.jsx
>          backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
✅

2024-01-23 11:52 UTC, nadiyniy commented on src/components/SeatList.jsx
> +function SeatList({ seats, handleSeatClick, reservedSeat, selectedSeat }) {
✅

2024-01-23 17:54 UTC, merged