task_3
nadiyniy/booking-cinema-tickets pull request #3
Opened 2024-01-24 14:32 UTC by nadiyniy

2024-01-26 22:50 UTC, mike-gusiev requested changes

2024-01-26 22:50 UTC, mike-gusiev commented on src/components/SessionList.tsx
> +import { Typography, Grid, Container } from '@mui/material';
погрупуй імпорти у всіх файлах. спочатку будуть іти імпорти бібліотек, потім відступ, потім імпорти компонентів, потім відступ, потім імпорт всього іншого

2024-01-26 22:50 UTC, mike-gusiev commented on src/components/SessionList.tsx
> +                sx={{ marginTop: '20px', marginBottom: '20px' }}
інлайнових стилів не повинно бути. перенеси все в styled components

2024-01-26 22:50 UTC, mike-gusiev commented on .eslintignore
> +src/index.tsx
перед відправкою пул реквеста на рев'ю переглядай файли свого пул реквесту на гітхабі. і виправиш все що помітиш самостійно, до того як мені відправляти на рев'ю.

якщо бачиш таку іконку, значить у цього файлу не вистачає переносу рядка в кінці.

2024-01-29 07:40 UTC, nadiyniy commented on src/components/SessionList.tsx
> +import { Typography, Grid, Container } from '@mui/material';
✅

2024-01-29 09:25 UTC, nadiyniy commented on src/components/SessionList.tsx
> +                sx={{ marginTop: '20px', marginBottom: '20px' }}
✅

2024-01-29 12:53 UTC, nadiyniy commented on .eslintignore
> +src/index.tsx
✅

2024-01-29 15:23 UTC, merged