GraphQL
nadiyniy/booking-cinema-tickets pull request #5
Opened 2024-02-02 15:17 UTC by nadiyniy

2024-02-06 18:26 UTC, mike-gusiev requested changes

2024-02-06 18:26 UTC, mike-gusiev commented on src/components/1.tsx
> +import { Box, TextField } from '@mui/material';
назови компонент нормальним іменем

2024-02-06 18:26 UTC, mike-gusiev commented on src/components/1.tsx
> +import { useState } from 'react';
погрупуй і посортуй імпорту

2024-02-06 18:26 UTC, mike-gusiev commented on src/components/1.tsx
> +const CreateTodo = ({ setAllTodos }: any) => {
any не можна використовувати

2024-02-06 18:26 UTC, mike-gusiev commented on src/components/SearchTodo.tsx
> +    const handleChangeValue = (e: any) => {
не використовуй одну букву для назви змінних. назва змінних має бути осмисленно

2024-02-06 18:26 UTC, mike-gusiev commented on vite.config.ts
> +    // build: {
не залишай закоментований код в репозиторії

2024-02-07 08:08 UTC, nadiyniy commented on src/components/SearchTodo.tsx
> +    const handleChangeValue = (e: any) => {
✅

2024-02-07 08:09 UTC, nadiyniy commented on vite.config.ts
> +    // build: {
✅

2024-02-08 16:30 UTC, merged